---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base/mongodb

namePrefix: dev-
images:
  - name: <MONGODB_IMAGE_NAME>
    newName: docker.io/library/mongo:latest
    newTag: dev
