apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      nodeSelector:
        eks.amazonaws.com/fargate-profile: example-fargate-profile
      containers:
      - name: mongodb
        image: mongo:6.0.3
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_URI
          value: mongodb://ts-db:27017/
        - name: MONGO_DB_NAME
          value: timeseries-visualization-test
        - name: MONGO_COLLECTION_NAME
          value: sensor_data
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongodb-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "example-storage-class"
      resources:
        requests:
          storage: 1Gi
