apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: data-consumer
  name: data-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      name: data-consumer
  strategy: {}
  template:
    metadata:
      labels:
        name: data-consumer
    spec:
      containers:
        - env:
            - name: MONGO_COLLECTION_NAME
              value: sensor_data
            - name: MONGO_DB_NAME
              value: timeseries-visualization-test
            - name: MONGO_URI
              value: mongodb://ts-db:27017/
            - name: MQTT_HOST
              value: mqtt-broker
            - name: MQTT_PORT
              value: "1883"
          image: data-consumer
          name: data-consumer
          resources: {}
      restartPolicy: Always
status: {}
