version: '3.2'

x-mongoenv: &mongoenv
  MONGO_URI: mongodb://ts-db:27017/
  MONGO_DB_NAME: timeseries-visualization-test
  MONGO_COLLECTION_NAME: sensor_data

x-mqttenv: &mqttenv
  MQTT_HOST: mqtt-broker
  MQTT_PORT: 1883

services:
  mongodb:
    container_name: ts-db
    image: mongo:6.0.3
    ports:
      - 27017:27017
  mqtt-broker:
    container_name: mqtt-broker
    build:
      context: mqtt-broker
    ports:
      - 1883:1883
    depends_on:
      - mongodb
  data-consumer:
    container_name: data-consumer
    build:
      context: data-consumer
      target: base
    environment:
      <<: *mongoenv
      <<: *mqttenv
    depends_on:
      - mqtt-broker
  ts-sensor-1:
    container_name: ts-sensor-1
    build:
      context: data-sensor
      target: base
    environment:
      <<: *mqttenv
      SENSOR_AREA: KITCHEN
      SENSOR_TYPE: TEMPERATURE
    depends_on:
      - data-consumer
  ts-sensor-2:
    container_name: ts-sensor-2
    build:
      context: data-sensor
      target: base
    environment:
      <<: *mqttenv
      SENSOR_AREA: KITCHEN
      SENSOR_TYPE: TEMPERATURE
    depends_on:
      - data-consumer
  ts-sensor-3:
    container_name: ts-sensor-3
    build:
      context: data-sensor
      target: base
    environment:
      <<: *mqttenv
      SENSOR_TYPE: HUMIDITY
      SENSOR_AREA: BEDROOM
    depends_on:
      - data-consumer
  ts-sensor-4:
    container_name: ts-sensor-4
    build:
      context: data-sensor
      target: base
    environment:
      <<: *mqttenv
      SENSOR_TYPE: TEMPERATURE
      SENSOR_AREA: BEDROOM
    depends_on:
      - data-consumer
  api:
    container_name: ts-api
    build:
      context: data-api
      target: base
    ports:
      - 8000:8000
    environment:
      <<: *mongoenv
    depends_on:
      - data-consumer
  angular-dashboard:
    container_name: angular-dashboard
    build:
      context: angular-dashboard
      target: prod
    ports:
      - 80:80
    depends_on:
      - api
  plotly-dashboard:
    container_name: plotly-dashboard
    build:
      context: plotly-dashboard
      target: base
    ports:
      - 8050:8050
    environment:
      <<: *mongoenv
    depends_on:
      - generator
    volumes:
      - ./plotly-dashboard/dashboard:/app/dashboard
    command: bash -c "python /app/dashboard/main.py"
