---
version: '3.2'

services:
  data-consumer:
    container_name: test-data-consumer
    build:
      context: data-consumer
      target: test
  ts-sensor:
    container_name: test-ts-sensor
    build:
      context: data-sensor
      target: test
  api:
    container_name: test-ts-api
    build:
      context: data-api
      target: test
  dashboard-angular:
    container_name: test-dashboard-angular
    privileged: true
    build:
      context: dashboard-angular
      target: test
    command: npm run ci
  dashboard-plotly:
    container_name: test-dashboard-plotly
    build:
      context: dashboard-plotly
      target: test
