---
version: '3.3'

x-mongoenv: &mongoenv
  MONGO_URI: mongodb://ts-db:27017/
  MONGO_DB_NAME: timeseries-visualization-test
  MONGO_COLLECTION_NAME: sensor_data

x-mqttenv: &mqttenv
  MQTT_HOST: mqtt-broker
  MQTT_PORT: 1883

services:
  ################################
  # data ingestion and storage
  ################################
  mongodb:
    container_name: ts-db
    image: mongo:6.0.3
    ports:
      - 27017:27017
  mqtt-broker:
    container_name: mqtt-broker
    build:
      context: mqtt-broker
    ports:
      - 1883:1883
    depends_on:
      - mongodb

  data-consumer:
    container_name: data-consumer
    build:
      context: data-consumer
      target: base
    environment:
      <<: [*mongoenv, *mqttenv]
    depends_on:
      - mqtt-broker
  ################################
  # REST API
  ################################
  api:
    container_name: ts-api
    build:
      context: data-api
      target: api
    ports:
      - 8000:8000
    environment:
      <<: *mongoenv
    depends_on:
      - data-consumer
  ################################
  # visualization dashboards
  ################################
  dashboard-angular:
    container_name: dashboard-angular
    build:
      context: dashboard-angular
      target: prod
    ports:
      - 80:80
    depends_on:
      - api
  dashboard-plotly:
    container_name: dashboard-plotly
    build:
      context: dashboard-plotly
      target: dash
    ports:
      - 8050:8050
    environment:
      <<: *mongoenv
    depends_on:
      - data-consumer
    volumes:
      - ./dashboard-plotly/dashboard:/app/dashboard
    command: bash -c "python /app/dashboard/main.py"
  dashboard-nicegui:
    container_name: dashboard-nicegui
    build:
      context: dashboard-nicegui
    ports:
      - 8060:8060
    environment:
      <<: *mongoenv
    depends_on:
      - data-consumer
    volumes:
      - ./dashboard-nicegui/dashboard:/app/dashboard
    command: bash -c "python /app/dashboard/main.py"
  ################################
  # sensors
  ################################
  ts-sensor-1:
    container_name: ts-sensor-1
    build:
      context: data-sensor
      target: sensor
    environment:
      <<: *mqttenv
      SENSOR_AREA: KITCHEN
      SENSOR_TYPE: TEMPERATURE
    depends_on:
      - data-consumer
  ts-sensor-2:
    container_name: ts-sensor-2
    build:
      context: data-sensor
      target: sensor
    environment:
      <<: *mqttenv
      SENSOR_AREA: KITCHEN
      SENSOR_TYPE: TEMPERATURE
    depends_on:
      - data-consumer
  ts-sensor-3:
    container_name: ts-sensor-3
    build:
      context: data-sensor
      target: sensor
    environment:
      <<: *mqttenv
      SENSOR_TYPE: HUMIDITY
      SENSOR_AREA: BEDROOM
    depends_on:
      - data-consumer
  ts-sensor-4:
    container_name: ts-sensor-4
    build:
      context: data-sensor
      target: sensor
    environment:
      <<: *mqttenv
      SENSOR_TYPE: TEMPERATURE
      SENSOR_AREA: BEDROOM
    depends_on:
      - data-consumer
