---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: mqtt-broker
  name: mqtt-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mqtt-broker
  strategy: {}
  template:
    metadata:
      labels:
        name: mqtt-broker
    spec:
      containers:
        - image: <MQTT_BROKER_IMAGE_NAME>
          name: mqtt-broker
          ports:
            - containerPort: 1883
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
      restartPolicy: Always
status: {}
