apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base/plotly-dash/

namePrefix: dev-
images:
- name: <PLOTLY_DASH_IMAGE_NAME>
  newName: my.image.registry/plotly-dash
  newTag: dev
