apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base/mqtt-broker/

namePrefix: dev-
images:
- name: <MQTT_BROKER_IMAGE_NAME>
  newName: my.image.registry/mqtt-broker
  newTag: dev
