---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base/mqtt-broker/

namePrefix: dev-
images:
  - name: <MQTT_BROKER_IMAGE_NAME>
    newName: docker.io/library/python-timeseries-exercise-mqtt-broker
    newTag: dev
