---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base/sensor

namePrefix: dev-
images:
  - name: <SENSOR_IMAGE_NAME>
    newName: docker.io/library/python-timeseries-exercise-ts-sensor-1
    newTag: dev
