---
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  list-python-projects:
    name: list python projects
    runs-on: ubuntu-latest
    outputs:
      projects: ${{ steps.list-projects.outputs.projects }}
    steps:
      - uses: actions/checkout@v2
      - name: List python projects
        id: list-projects
        run: |
          echo "::set-output name=projects::$(find . -name "pyproject.toml" -exec dirname {} \; | jq --raw-input --slurp -c 'split("\n") | .[0:-1]')"
  tests:
    name: run tests
    runs-on: ubuntu-latest
    needs: list-python-projects
    strategy:
      matrix:
        project: ${{ fromJson(needs.list-python-projects.outputs.projects) }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pushd ${{ matrix.project }}
          test -f requirements.txt && pip install -r requirements.txt
          test -f requirements-dev.txt && pip install -r requirements-dev.txt
      - name: Run tests
        run: |
          pushd ${{ matrix.project }}
          python -m pytest
      - name: Report coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ${{ matrix.project }}/coverage.xml
          env_vars: OS,PYTHON
          fail_ci_if_error: true
          verbose: true
